spring:
  config:
    import: optional:configserver:http://localhost:8000
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/notification
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:microservice.notification_service.kafka.order.OrderConfirmation,paymentConfirmation:microservice.notification_service.kafka.payment.PaymentConfirmation
  mail:
    host: smtp.hostinger.com
    port: 587
    username: phamduykhanh@langmaster247.com
    password: Bin@2710
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
    default-encoding: UTF-8