services:
  mysql:
    image: mysql
    ports:
      - "3305:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: microservice
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservice

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command: start-dev
    ports:
      - "9090:8080"
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:mysql://mysql:3306/microservice
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    networks:
      - microservice

  redis:
    image: redis:6.2-alpine
    hostname: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - microservice
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-config:/config
      - neo4j-plugins:/plugins
    networks:
      - microservice

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservice

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092, PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - microservice

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - microservice

  mongodb:
    image: mongo:latest
    ports:
      - "27016:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    networks:
      - microservice

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservice

  config-server:
     build:
       context: .
       dockerfile: config-server/Dockerfile
     hostname: config-server
     ports:
       - "8000:8000"
     networks:
       - microservice
     restart: on-failure
     env_file:
       - local.env

  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    restart: on-failure
    networks:
      - microservice
    env_file:
      - local.env

  monitor-admin:
    build:
      context: .
      dockerfile: monitor-admin/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - config-server
      - discovery-service
    restart: on-failure
    networks:
      - microservice
    env_file:
      - local.env

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-service
      - keycloak
      - redis
    restart: on-failure
    networks:
      - microservice
    env_file:
      - local.env

  authentication-service:
    build:
      context: .
      dockerfile: authentication-service/Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - config-server
      - discovery-service
      - keycloak
      - mysql
    restart: on-failure
    networks:
      - microservice
    env_file:
      - local.env

  profile-service:
    build:
      context: .
      dockerfile: profile-service/Dockerfile
    ports:
      - "8200:8200"
    depends_on:
      - config-server
      - discovery-service
      - keycloak
      - neo4j
    restart: on-failure
    networks:
      - microservice
    env_file:
      - local.env

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "8300:8300"
    depends_on:
      - config-server
      - discovery-service
      - keycloak
      - mysql
    restart: on-failure
    networks:
      - microservice
    env_file:
      - local.env

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8400:8400"
    depends_on:
      - config-server
      - discovery-service
      - keycloak
      - mysql
      - product-service
      - payment-service
      - notification-service
    restart: on-failure
    networks:
      - microservice
    env_file:
      - local.env

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8500:8500"
    depends_on:
      - config-server
      - discovery-service
      - keycloak
      - mysql
      - notification-service
    restart: on-failure
    networks:
      - microservice
    env_file:
      - local.env

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8600:8600"
    depends_on:
      - config-server
      - discovery-service
      - kafka
      - zookeeper
    restart: on-failure
    networks:
      - microservice
    env_file:
      - local.env



networks:
  microservice:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  neo4j-data:
  neo4j-logs:
  neo4j-config:
  neo4j-plugins:
  mongo-data:
