spring:
  config:
    import: optional:configserver:http://localhost:8000
  application:
    name: authentication-service
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/microservice?createDatabaseIfNotExist=true
    username: root
    password: Bin@2710
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  keycloak:
    admin:
      clientId: microservice
      clientSecret: 6dTqkrZIIoARcjzG3qjVfU0Sc77rConI
    realm: microservice
    serverUrl: http://localhost:9090
    issuer-uri: "http://localhost:9090/realms/microservice"