spring:
  config:
    import: optional:configserver:http://config-server:8000
  application:
    name: profile-service
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/microservice"

app:
  keycloak:
    admin:
      clientId: microservice
    issuer-uri: "http://keycloak:8080/realms/microservice"

eureka:
  instance:
    hostname: discovery-service
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true