eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka/

spring:
  cloud:
    config:
      override-system-properties: false
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://${ZIPKIN_HOST:localhost}:9411

logging:
  level:
    root: INFO

app:
  keycloak:
    admin:
      clientId: microservice
      clientSecret: ${KEYCLOAK_ID:AwN1jMOWGrWtAxPHRjnj6oMmT1keH285}
    realm: microservice
    serverUrl: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

