eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka/

spring:
  cloud:
    config:
      override-system-properties: false

app:
  keycloak:
    admin:
      clientId: microservice
      clientSecret: ${KEYCLOAK_ID:YcqqOtQr5AwXaxCJIJucop0A5FpHjuhQ}
    realm: microservice
    serverUrl: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

