server:
  port: 8100

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9090}/realms/microservice

info:
  app:
    name: "Authentication Service"
    description: "Authentication service of Microservice"
    version: 1.0.0