server:
  port: 8761

eureka:
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
    preferIpAddress: ${PREFER_IP_ADDRESS:false}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  cloud:
    config:
      override-system-properties: false
