server:
  port: 8761

eureka:
#  instance:
#    hostname: ${HOST_IP_ADDRESS:localhost}
  client:
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${DISCOVERY_HOST:localhost}:${server.port}/eureka/
    register-with-eureka: false
    client.fetch-registry: false
spring:
  cloud:
    config:
      override-system-properties: false
